import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 1. 对应 presets 里的默认 docs (讲义)
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 2. 对应 plugins 里的 embedded 实例
  // 注意：这里的 key (embeddedSidebar) 可以随便取，但要记住它
  embeddedSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;